<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:12
 */

namespace app\wap\controller;


class Feedback extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 意见反馈
     */
    public function feedback_add(){
        $model_mb_feedback = Model('mbfeedback');

        $param = array();
        $param['content'] = $_POST['feedback'];

        $param['type'] = $this->member_info['client_type'];
        $param['ftime'] = TIMESTAMP;
        $param['member_id'] = $this->member_info['member_id'];
        $param['member_name'] = $this->member_info['member_name'];
//        $param['member_mobile'] = input('member_mobile');
        if(empty($param['content']))output_error('反馈内容不能为空');
//        if(empty($param['member_mobile']))output_error('手机号码不能为空');
        $result = $model_mb_feedback->addMbFeedback($param);

        if ($result) {
            output_data(array('state'=>true));
        }
        else {
            output_error('保存失败');
        }
    }
}